export enum TransactionCategories {
  // Broad
  Food = 'Food',
  Health = 'Health',
  Utilities = 'Utilities',
  Transport = 'Transport',
  Lifestyle = 'Lifestyle',
  Household = 'Household',
  ProfessionalFees = 'Professional Fees',

  // Group
  ElectricityGasAndWater = 'Electricity gas & water supply',
  BuildersSupplies = "Builder's supplies wholesaling",
  SupermarketAndGroceryStores = 'Supermarket and grocery stores',
  SpecialisedFoodRetailing = 'Specialised food retailing',
  ParksAndGardens = 'Parks & gardens',
  OtherInsurance = 'Other insurance',
  CafesAndRestaurants = 'Cafes & restaurants',
  MedicalAndDentalServices = 'Medical & dental services',
  PostalAndCourierServices = 'Postal & courier services',
  RadioAndTelevisionServices = 'Radio & television services',
  ServicesToTheArts = 'Services to the arts',
  MachineryAndEquipmentWholesaling = 'Machinery & equipment wholesaling',
  ServicesToRoadTransport = 'Services to road transport',
  OtherPersonalServices = 'Other personal services',
  Uncategorised = 'Uncategorised',

  // Base
  UtilisingElectricGasWaterAndSanitary = 'Utilising – Electric, Gas, Water and Sanitary',
  HardwareEquipmentAndSupplies = 'Hardware equipment & supplies',
  AutomotiveServiceShopsNonDealer = 'Automotive Service Shops (Non-Dealer)',
  GroceryStoresAndSupermarkets = 'Grocery Stores and Supermarkets',
  PackageStoresBeerWineAndLiquor = 'Package Stores – Beer, Wine and Liquor',
  EntertainmentNEC = 'Entertainment (NEC)',
  InsuranceSalesUnderwritingAndPremiums = 'Insurance Sales, Underwriting and Premiums',
  DoctorsAndPhysicians = 'Doctors and Physicians',
  TelecommunicationServices = 'Telecommunication Services',
  CableServices = 'Cable services',
  FastFoodRestaurants = 'Fast food restaurants',
  EventsAndTickets = 'Events & tickets',
  ComputersEquipmentAndSoftware = 'Computers, Computer Peripheral Equipment and Software',
  MiscellaneousFoodStoresConvenienceStoresAndSpecialtyMarkets = 'Miscellaneous Food Stores – Convenience Stores and Specialty Markets',
  ParkingLotsAndGarages = 'Parking lots & garages',
  TelecommunicationsEquipmentAndTelephoneSales = 'Telecommunications Equipment and Telephone Sales',
  ServiceStations = 'Service Stations',
  HealthAndBeautySpas = 'Health & beauty spas',
  PostalServicesGovernmentOnly = 'Postal Services – Government Only',
}
