// Higher level grouping
export enum TransactionCategoryGroupName {
  Appearance = 'Appearance',
  Education = 'Education',
  Food = 'Food',
  Health = 'Health',
  Household = 'Household',
  Lifestyle = 'Lifestyle',
  ProfessionalServices = 'Professional Services',
  Transport = 'Transport',
  Utilities = 'Utilities',
}

// https://nzfcc.org/explore/
export enum TransactionCategoryName {
  Appearance_ApparelAndAccessoryStores = 'Apparel and Accessory Stores',
  Appearance_ChildAndInfantClothing = 'Child and Infant Clothing',
  Appearance_ClothingAlterationAndRepair = 'Clothing Alteration and Repair',
  Appearance_ClothingRental = 'Clothing Rental',
  Appearance_ClothingStores = 'Clothing Stores',
  Appearance_CosmeticSupplies = 'Cosmetic Supplies',
  Appearance_FabricSewingKnittingAndRelatedSupplies = 'Fabric, Sewing, Knitting and Related Supplies',
  Appearance_HaircutsAndTreatments = 'Haircuts and Treatments',
  Appearance_SecondhandAndOpportunityStores = 'Secondhand and Opportunity Stores',
  Appearance_ShoeStores = 'Shoe Stores',
  Appearance_UniformsAndCommercialClothing = 'Uniforms and Commercial Clothing',
  Appearance_WatchClockAndJewelleryStoresAndServices = 'Watch, Clock and Jewellery Stores and Services',

  Education_BookStores = 'Book Stores',
  Education_ChildcareServices = 'Childcare Services',
  Education_EducationNotElsewhereClassified = 'Education (not elsewhere classified)',
  Education_Libraries = 'Libraries',
  Education_NewspapersMagazinesAndLiterarySubscriptions = 'Newspapers, Magazines and Literary Subscriptions',
  Education_PerformingArtTraining = 'Performing Art Training',
  Education_PrimaryAndSecondarySchools = 'Primary and Secondary Schools',
  Education_UniversitiesProfessionalSchoolsAndOtherTertiaryEducation = 'Universities, Professional Schools and Other Tertiary Education',

  Food_Bakeries = 'Bakeries',
  Food_ConvenienceStores = 'Convenience Stores',
  Food_FishAndSeafoodSupplies = 'Fish and Seafood Supplies',
  Food_IceCreamGelatoNutAndConfectionaryStores = 'Ice Cream, Gelato, Nut and Confectionary Stores',
  Food_MealKitStores = 'Meal Kit Stores',
  Food_MeatSupplies = 'Meat Supplies',
  Food_SpecialtyFoodStores = 'Specialty Food Stores',
  Food_SupermarketsAndGroceryStores = 'Supermarkets and Grocery Stores',

  Health_ChiropodistsAndPodiatrists = 'Chiropodists and Podiatrists',
  Health_ChiropractorsAndOsteopaths = 'Chiropractors and Osteopaths',
  Health_DentalAndMedicalLaboratories = 'Dental and Medical Laboratories',
  Health_DentalServices = 'Dental Services',
  Health_DoctorsAndPhysicians = 'Doctors and Physicians',
  Health_GymsFitnessAquaticFacilitiesYogaPilates = 'Gyms, Fitness, Aquatic Facilities, Yoga, Pilates',
  Health_Hospices = 'Hospices',
  Health_HospitalsAndEmergencyCare = 'Hospitals and emergency care',
  Health_MedicalProductsAndSupplies = 'Medical products and supplies (not elsewhere classified)',
  Health_MedicalServices = 'Medical services',
  Health_OptometristsAndEyewear = 'Optometrists and eyewear',
  Health_Pharmacies = 'Pharmacies',
  Health_PhysiotherapyAndMassageTherapy = 'Physiotherapy and massage therapy',
  Health_PsychologyPsychiatricCounsellingAndOtherMentalHealthServices = 'Psychology, psychiatric, counselling, and other mental health services',
  Health_SportsAndAthleticClubs = 'Sports and athletic clubs',
  Health_VeterinaryServices = 'Veterinary services',

  //Household TODO, add

  //Housing TODO, add

  Lifestyle_AirTransportServices = 'Air transport services',
  Lifestyle_Airports = 'Airports',
  Lifestyle_ArtAndCraftSupplies = 'Art and craft supplies',
  Lifestyle_ArtStoresDealersAndGalleries = 'Art stores, dealers, and galleries',
  Lifestyle_AttractionsMuseumsZoosAmusementParksCircusesExhibits = 'Attractions, museums, zoos, amusement parks, circuses, exhibits',
  Lifestyle_BarsPubsNightclubs = 'Bars, pubs, nightclubs',
  Lifestyle_BoatDealers = 'Boat dealers',
  Lifestyle_BoatRentals = 'Boat rentals',
  Lifestyle_CafesAndRestaurants = 'Cafes and restaurants',
  Lifestyle_CasinoLotteryAndOtherGamblingServices = 'Casino, lottery, and other gambling services',
  Lifestyle_Caterers = 'Caterers',
  Lifestyle_CigaretteVapeAndOtherSmokingProducts = 'Cigarette, vape, and other smoking products',
  Lifestyle_Cinemas = 'Cinemas',
  Lifestyle_CosmeticHealthSpasAndRelaxationMassageServices = 'Cosmetic, health spas, and relaxation massage services',
  Lifestyle_DatingAndMatchmakingServices = 'Dating and matchmaking services',
  Lifestyle_DigitalGamingProductsAndServices = 'Digital gaming products and services',
  Lifestyle_DutyFreeStores = 'Duty free stores',
  Lifestyle_Entertainment = 'Entertainment (not elsewhere classified)',
  Lifestyle_EventsAndTickets = 'Events and tickets (not elsewhere classified)',
  Lifestyle_FastFoodStores = 'Fast food stores',
  Lifestyle_FloralSuppliesAndServices = 'Floral supplies and services',
  Lifestyle_GiftAndSouvenirStores = 'Gift and souvenir stores',
  Lifestyle_GolfCourses = 'Golf courses',
  Lifestyle_HobbyToyAndPhysicalGameStores = 'Hobby, toy, and physical game stores',
  Lifestyle_HotelsMotelsAndOtherTemporaryAccommodation = 'Hotels, motels, and other temporary accommodation',
  Lifestyle_LiquorStores = 'Liquor stores',
  Lifestyle_MarinasMarineSuppliesAndMarineServices = 'Marinas, marine supplies, and marine services',
  Lifestyle_MediaAndEntertainmentStreamingServices = 'Media and entertainment streaming services',
  Lifestyle_MotorParksCampgroundsHolidayParksRecreationalCamps = 'Motor parks, campgrounds, holiday parks, recreational camps',
  Lifestyle_MusicalEquipmentRecordingsAndSupplies = 'Musical equipment, recordings, and supplies',
  Lifestyle_PhotographyEquipmentAndServices = 'Photography equipment and services',
  Lifestyle_SportsEquipmentAndSupplies = 'Sports equipment and supplies',
  Lifestyle_TheatreConcertsAndOtherArtisticPerformances = 'Theatre, concerts, and other artistic performances',
  Lifestyle_TravelAgenciesAndTourOperators = 'Travel agencies and tour operators',
  Lifestyle_WelfareAndCharity = 'Welfare and charity',
  Lifestyle_WineriesBreweriesAndDistilleries = 'Wineries, breweries, and distilleries',

  //Professional Services TODO, add

  //Transport TODO, add

  Utilities_ElectricityAndGasServices = 'Electricity and gas services',
  Utilities_ElectricityServices = 'Electricity services',
  Utilities_GasServices = 'Gas services',
  Utilities_InternetServices = 'Internet services',
  Utilities_TelecommunicationServices = 'Telecommunication services',
  Utilities_WaterAndSanitationServices = 'Water and sanitation services',
}
